title: Your Arlington
description: A local non-profit dedicated to providing citizen journalism to Arlington, MA.
theme: minima
minima:
  skin: solarized

# Customizations from https://github.com/jekyll/minima
minima:
  social_links:
    - platform: twitter
      user_url: "https://twitter.com/yourarlington"
      title: Your Arlington On Twitter

include:
  - _pages

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
