title: Your Arlington
description: A local non-profit dedicated to providing citizen journalism to Arlington, MA.
theme: minima

# Customizations from https://github.com/jekyll/minima version 2.5.1
twitter_username: yourarlington

# Customizations for jekyll-seo-tag
twitter:
  username: yourarlington
  card: summary
social:
  name: Your Arlington
  links:
    - https://twitter.com/YourArlington

# Jekyll settings
include:
  - _pages

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
